export default {
    SET_SEARCH_VALUE: 'app/SET_SEARCH_VALUE',
    SET_SEARCH_PLACEHOLDER: 'app/SET_SEARCH_PLACEHOLDER',

    FETCH_USER: 'app/FETCH_USER',
    FETCH_USER_SUCCESS: 'app/FETCH_USER_SUCCESS',
    FETCH_USER_FAIL: 'app/FETCH_USER_FAIL',

    UPDATE_USER_TOKEN: 'app/UPDATE_USER_TOKEN',
    UPDATE_USER_TOKEN_SUCCESS: 'app/UPDATE_USER_TOKEN_SUCCESS',
    UPDATE_USER_TOKEN_FAIL: 'app/UPDATE_USER_TOKEN_FAIL',

    START_PROGRESS: 'app/START_PROGRESS',
    SET_PROGRESS: 'app/SET_PROGRESS',
    COMPLETE_PROGRESS: 'app/COMPLETE_PROGRESS',
    RESET_PROGRESS: 'app/RESET_PROGRESS',
};
