#!/bin/bash

TIMESTAMP=$(date +%Y%m%d%H%M%S)  
DOCKER=docker
IMAGE_NAME=dstack
TIMESTAMPED_TAG=$TIMESTAMP
LATEST_TAG=latest
LATEST_MASTER_TAG=latest-master
RELEASE_VERSION_TAG=$VERSION
DOCKER_REGISTRY=dstackai
DOCKER_USER=dstackai
REGISTRY_IMAGE_FULL_PATH_LATEST=$DOCKER_REGISTRY/$IMAGE_NAME:$LATEST_TAG
REGISTRY_IMAGE_FULL_PATH_LATEST_MASTER=$DOCKER_REGISTRY/$IMAGE_NAME:$LATEST_MASTER_TAG
REGISTRY_IMAGE_FULL_PATH=$DOCKER_REGISTRY/$IMAGE_NAME:$TIMESTAMPED_TAG
REGISTRY_IMAGE_FULL_PATH_RELEASE=$DOCKER_REGISTRY/$IMAGE_NAME:$RELEASE_VERSION_TAG
