export default {
    FETCH_CURRENT_USER: 'app/user/FETCH',
    FETCH_CURRENT_USER_SUCCESS: 'app/user/FETCH_SUCCESS',
    FETCH_CURRENT_USER_FAIL: 'app/user/FETCH_FAIL',

    FETCH_CONFIG_INFO: 'app/config/FETCH',
    FETCH_CONFIG_INFO_SUCCESS: 'app/config/FETCH_SUCCESS',
    FETCH_CONFIG_INFO_FAIL: 'app/config/FETCH_FAIL',

    START_PROGRESS: 'app/START_PROGRESS',
    SET_PROGRESS: 'app/SET_PROGRESS',
    COMPLETE_PROGRESS: 'app/COMPLETE_PROGRESS',
    RESET_PROGRESS: 'app/RESET_PROGRESS',
};
